// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.21.12
// source: material.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MaterialResponse_Status int32

const (
	MaterialResponse_OK    MaterialResponse_Status = 0
	MaterialResponse_ERROR MaterialResponse_Status = 1
)

// Enum value maps for MaterialResponse_Status.
var (
	MaterialResponse_Status_name = map[int32]string{
		0: "OK",
		1: "ERROR",
	}
	MaterialResponse_Status_value = map[string]int32{
		"OK":    0,
		"ERROR": 1,
	}
)

func (x MaterialResponse_Status) Enum() *MaterialResponse_Status {
	p := new(MaterialResponse_Status)
	*p = x
	return p
}

func (x MaterialResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MaterialResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_material_proto_enumTypes[0].Descriptor()
}

func (MaterialResponse_Status) Type() protoreflect.EnumType {
	return &file_material_proto_enumTypes[0]
}

func (x MaterialResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MaterialResponse_Status.Descriptor instead.
func (MaterialResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_material_proto_rawDescGZIP(), []int{1, 0}
}

type ItemResponse_Status int32

const (
	ItemResponse_OK    ItemResponse_Status = 0
	ItemResponse_ERROR ItemResponse_Status = 1
)

// Enum value maps for ItemResponse_Status.
var (
	ItemResponse_Status_name = map[int32]string{
		0: "OK",
		1: "ERROR",
	}
	ItemResponse_Status_value = map[string]int32{
		"OK":    0,
		"ERROR": 1,
	}
)

func (x ItemResponse_Status) Enum() *ItemResponse_Status {
	p := new(ItemResponse_Status)
	*p = x
	return p
}

func (x ItemResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ItemResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_material_proto_enumTypes[1].Descriptor()
}

func (ItemResponse_Status) Type() protoreflect.EnumType {
	return &file_material_proto_enumTypes[1]
}

func (x ItemResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ItemResponse_Status.Descriptor instead.
func (ItemResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_material_proto_rawDescGZIP(), []int{6, 0}
}

type OrderResponse_Status int32

const (
	OrderResponse_OK    OrderResponse_Status = 0
	OrderResponse_ERROR OrderResponse_Status = 1
)

// Enum value maps for OrderResponse_Status.
var (
	OrderResponse_Status_name = map[int32]string{
		0: "OK",
		1: "ERROR",
	}
	OrderResponse_Status_value = map[string]int32{
		"OK":    0,
		"ERROR": 1,
	}
)

func (x OrderResponse_Status) Enum() *OrderResponse_Status {
	p := new(OrderResponse_Status)
	*p = x
	return p
}

func (x OrderResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_material_proto_enumTypes[2].Descriptor()
}

func (OrderResponse_Status) Type() protoreflect.EnumType {
	return &file_material_proto_enumTypes[2]
}

func (x OrderResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderResponse_Status.Descriptor instead.
func (OrderResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_material_proto_rawDescGZIP(), []int{12, 0}
}

// Material messages
type Material struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Material_ID   uint32  `protobuf:"varint,1,opt,name=Material_ID,json=MaterialID,proto3" json:"Material_ID,omitempty"`
	Material_Name string  `protobuf:"bytes,2,opt,name=Material_Name,json=MaterialName,proto3" json:"Material_Name,omitempty"`
	Description   string  `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	Stock         int32   `protobuf:"varint,4,opt,name=Stock,proto3" json:"Stock,omitempty"`
	Price         float64 `protobuf:"fixed64,5,opt,name=Price,proto3" json:"Price,omitempty"`
}

func (x *Material) Reset() {
	*x = Material{}
	mi := &file_material_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Material) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Material) ProtoMessage() {}

func (x *Material) ProtoReflect() protoreflect.Message {
	mi := &file_material_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Material.ProtoReflect.Descriptor instead.
func (*Material) Descriptor() ([]byte, []int) {
	return file_material_proto_rawDescGZIP(), []int{0}
}

func (x *Material) GetMaterial_ID() uint32 {
	if x != nil {
		return x.Material_ID
	}
	return 0
}

func (x *Material) GetMaterial_Name() string {
	if x != nil {
		return x.Material_Name
	}
	return ""
}

func (x *Material) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Material) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *Material) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type MaterialResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  MaterialResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=pb.MaterialResponse_Status" json:"status,omitempty"`
	Message string                  `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are assignable to Payload:
	//
	//	*MaterialResponse_Error
	//	*MaterialResponse_Data
	Payload isMaterialResponse_Payload `protobuf_oneof:"payload"`
}

func (x *MaterialResponse) Reset() {
	*x = MaterialResponse{}
	mi := &file_material_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaterialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaterialResponse) ProtoMessage() {}

func (x *MaterialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_material_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaterialResponse.ProtoReflect.Descriptor instead.
func (*MaterialResponse) Descriptor() ([]byte, []int) {
	return file_material_proto_rawDescGZIP(), []int{1}
}

func (x *MaterialResponse) GetStatus() MaterialResponse_Status {
	if x != nil {
		return x.Status
	}
	return MaterialResponse_OK
}

func (x *MaterialResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (m *MaterialResponse) GetPayload() isMaterialResponse_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *MaterialResponse) GetError() string {
	if x, ok := x.GetPayload().(*MaterialResponse_Error); ok {
		return x.Error
	}
	return ""
}

func (x *MaterialResponse) GetData() string {
	if x, ok := x.GetPayload().(*MaterialResponse_Data); ok {
		return x.Data
	}
	return ""
}

type isMaterialResponse_Payload interface {
	isMaterialResponse_Payload()
}

type MaterialResponse_Error struct {
	Error string `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

type MaterialResponse_Data struct {
	Data string `protobuf:"bytes,4,opt,name=data,proto3,oneof"`
}

func (*MaterialResponse_Error) isMaterialResponse_Payload() {}

func (*MaterialResponse_Data) isMaterialResponse_Payload() {}

type MaterialNoParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MaterialNoParams) Reset() {
	*x = MaterialNoParams{}
	mi := &file_material_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaterialNoParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaterialNoParams) ProtoMessage() {}

func (x *MaterialNoParams) ProtoReflect() protoreflect.Message {
	mi := &file_material_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaterialNoParams.ProtoReflect.Descriptor instead.
func (*MaterialNoParams) Descriptor() ([]byte, []int) {
	return file_material_proto_rawDescGZIP(), []int{2}
}

type MaterialList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Materials []*Material `protobuf:"bytes,1,rep,name=Materials,proto3" json:"Materials,omitempty"`
}

func (x *MaterialList) Reset() {
	*x = MaterialList{}
	mi := &file_material_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaterialList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaterialList) ProtoMessage() {}

func (x *MaterialList) ProtoReflect() protoreflect.Message {
	mi := &file_material_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaterialList.ProtoReflect.Descriptor instead.
func (*MaterialList) Descriptor() ([]byte, []int) {
	return file_material_proto_rawDescGZIP(), []int{3}
}

func (x *MaterialList) GetMaterials() []*Material {
	if x != nil {
		return x.Materials
	}
	return nil
}

type MaterialID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID uint32 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"` // Corrected typo
}

func (x *MaterialID) Reset() {
	*x = MaterialID{}
	mi := &file_material_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaterialID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaterialID) ProtoMessage() {}

func (x *MaterialID) ProtoReflect() protoreflect.Message {
	mi := &file_material_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaterialID.ProtoReflect.Descriptor instead.
func (*MaterialID) Descriptor() ([]byte, []int) {
	return file_material_proto_rawDescGZIP(), []int{4}
}

func (x *MaterialID) GetID() uint32 {
	if x != nil {
		return x.ID
	}
	return 0
}

// Item messages
type Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item_ID         uint32  `protobuf:"varint,1,opt,name=Item_ID,json=ItemID,proto3" json:"Item_ID,omitempty"`
	Item_Name       string  `protobuf:"bytes,2,opt,name=Item_Name,json=ItemName,proto3" json:"Item_Name,omitempty"`
	Material_ID     uint32  `protobuf:"varint,3,opt,name=Material_ID,json=MaterialID,proto3" json:"Material_ID,omitempty"`
	Length          uint32  `protobuf:"varint,4,opt,name=Length,proto3" json:"Length,omitempty"`
	Width           uint32  `protobuf:"varint,5,opt,name=Width,proto3" json:"Width,omitempty"`
	Fixed_Size_ID   uint32  `protobuf:"varint,6,opt,name=Fixed_Size_ID,json=FixedSizeID,proto3" json:"Fixed_Size_ID,omitempty"`
	Is_Custom       bool    `protobuf:"varint,7,opt,name=Is_Custom,json=IsCustom,proto3" json:"Is_Custom,omitempty"`
	Estimated_Price float32 `protobuf:"fixed32,8,opt,name=Estimated_Price,json=EstimatedPrice,proto3" json:"Estimated_Price,omitempty"`
	User_ID         uint32  `protobuf:"varint,9,opt,name=User_ID,json=UserID,proto3" json:"User_ID,omitempty"`
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_material_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_material_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_material_proto_rawDescGZIP(), []int{5}
}

func (x *Item) GetItem_ID() uint32 {
	if x != nil {
		return x.Item_ID
	}
	return 0
}

func (x *Item) GetItem_Name() string {
	if x != nil {
		return x.Item_Name
	}
	return ""
}

func (x *Item) GetMaterial_ID() uint32 {
	if x != nil {
		return x.Material_ID
	}
	return 0
}

func (x *Item) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *Item) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Item) GetFixed_Size_ID() uint32 {
	if x != nil {
		return x.Fixed_Size_ID
	}
	return 0
}

func (x *Item) GetIs_Custom() bool {
	if x != nil {
		return x.Is_Custom
	}
	return false
}

func (x *Item) GetEstimated_Price() float32 {
	if x != nil {
		return x.Estimated_Price
	}
	return 0
}

func (x *Item) GetUser_ID() uint32 {
	if x != nil {
		return x.User_ID
	}
	return 0
}

type ItemResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  ItemResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=pb.ItemResponse_Status" json:"status,omitempty"`
	Message string              `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are assignable to Payload:
	//
	//	*ItemResponse_Error
	//	*ItemResponse_Data
	Payload isItemResponse_Payload `protobuf_oneof:"payload"`
}

func (x *ItemResponse) Reset() {
	*x = ItemResponse{}
	mi := &file_material_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemResponse) ProtoMessage() {}

func (x *ItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_material_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemResponse.ProtoReflect.Descriptor instead.
func (*ItemResponse) Descriptor() ([]byte, []int) {
	return file_material_proto_rawDescGZIP(), []int{6}
}

func (x *ItemResponse) GetStatus() ItemResponse_Status {
	if x != nil {
		return x.Status
	}
	return ItemResponse_OK
}

func (x *ItemResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (m *ItemResponse) GetPayload() isItemResponse_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *ItemResponse) GetError() string {
	if x, ok := x.GetPayload().(*ItemResponse_Error); ok {
		return x.Error
	}
	return ""
}

func (x *ItemResponse) GetData() string {
	if x, ok := x.GetPayload().(*ItemResponse_Data); ok {
		return x.Data
	}
	return ""
}

type isItemResponse_Payload interface {
	isItemResponse_Payload()
}

type ItemResponse_Error struct {
	Error string `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

type ItemResponse_Data struct {
	Data string `protobuf:"bytes,4,opt,name=data,proto3,oneof"`
}

func (*ItemResponse_Error) isItemResponse_Payload() {}

func (*ItemResponse_Data) isItemResponse_Payload() {}

type ItemID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID uint32 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"` // Corrected typo
}

func (x *ItemID) Reset() {
	*x = ItemID{}
	mi := &file_material_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemID) ProtoMessage() {}

func (x *ItemID) ProtoReflect() protoreflect.Message {
	mi := &file_material_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemID.ProtoReflect.Descriptor instead.
func (*ItemID) Descriptor() ([]byte, []int) {
	return file_material_proto_rawDescGZIP(), []int{7}
}

func (x *ItemID) GetID() uint32 {
	if x != nil {
		return x.ID
	}
	return 0
}

type ItemList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*Item `protobuf:"bytes,1,rep,name=Items,proto3" json:"Items,omitempty"`
}

func (x *ItemList) Reset() {
	*x = ItemList{}
	mi := &file_material_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemList) ProtoMessage() {}

func (x *ItemList) ProtoReflect() protoreflect.Message {
	mi := &file_material_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemList.ProtoReflect.Descriptor instead.
func (*ItemList) Descriptor() ([]byte, []int) {
	return file_material_proto_rawDescGZIP(), []int{8}
}

func (x *ItemList) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type ItemNoParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ItemNoParams) Reset() {
	*x = ItemNoParams{}
	mi := &file_material_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemNoParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemNoParams) ProtoMessage() {}

func (x *ItemNoParams) ProtoReflect() protoreflect.Message {
	mi := &file_material_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemNoParams.ProtoReflect.Descriptor instead.
func (*ItemNoParams) Descriptor() ([]byte, []int) {
	return file_material_proto_rawDescGZIP(), []int{9}
}

// Order messages
type Order struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Order_ID   uint32  `protobuf:"varint,1,opt,name=Order_ID,json=OrderID,proto3" json:"Order_ID,omitempty"`
	User_ID    uint32  `protobuf:"varint,2,opt,name=User_ID,json=UserID,proto3" json:"User_ID,omitempty"`
	Item_ID    uint32  `protobuf:"varint,3,opt,name=Item_ID,json=ItemID,proto3" json:"Item_ID,omitempty"`
	Quantity   int32   `protobuf:"varint,4,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	Status     string  `protobuf:"bytes,5,opt,name=Status,proto3" json:"Status,omitempty"`
	CustomCut  string  `protobuf:"bytes,6,opt,name=Custom_cut,json=CustomCut,proto3" json:"Custom_cut,omitempty"`
	Is_Custom  bool    `protobuf:"varint,7,opt,name=Is_Custom,json=IsCustom,proto3" json:"Is_Custom,omitempty"`
	Amount     float64 `protobuf:"fixed64,8,opt,name=Amount,proto3" json:"Amount,omitempty"`
	Payment_ID string  `protobuf:"bytes,9,opt,name=Payment_ID,json=PaymentID,proto3" json:"Payment_ID,omitempty"`
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_material_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_material_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_material_proto_rawDescGZIP(), []int{10}
}

func (x *Order) GetOrder_ID() uint32 {
	if x != nil {
		return x.Order_ID
	}
	return 0
}

func (x *Order) GetUser_ID() uint32 {
	if x != nil {
		return x.User_ID
	}
	return 0
}

func (x *Order) GetItem_ID() uint32 {
	if x != nil {
		return x.Item_ID
	}
	return 0
}

func (x *Order) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Order) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Order) GetCustomCut() string {
	if x != nil {
		return x.CustomCut
	}
	return ""
}

func (x *Order) GetIs_Custom() bool {
	if x != nil {
		return x.Is_Custom
	}
	return false
}

func (x *Order) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Order) GetPayment_ID() string {
	if x != nil {
		return x.Payment_ID
	}
	return ""
}

type OrderList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Orders []*Order `protobuf:"bytes,1,rep,name=Orders,proto3" json:"Orders,omitempty"`
}

func (x *OrderList) Reset() {
	*x = OrderList{}
	mi := &file_material_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderList) ProtoMessage() {}

func (x *OrderList) ProtoReflect() protoreflect.Message {
	mi := &file_material_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderList.ProtoReflect.Descriptor instead.
func (*OrderList) Descriptor() ([]byte, []int) {
	return file_material_proto_rawDescGZIP(), []int{11}
}

func (x *OrderList) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type OrderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  OrderResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=pb.OrderResponse_Status" json:"status,omitempty"`
	Message string               `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are assignable to Payload:
	//
	//	*OrderResponse_Error
	//	*OrderResponse_Data
	Payload isOrderResponse_Payload `protobuf_oneof:"payload"`
}

func (x *OrderResponse) Reset() {
	*x = OrderResponse{}
	mi := &file_material_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderResponse) ProtoMessage() {}

func (x *OrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_material_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderResponse.ProtoReflect.Descriptor instead.
func (*OrderResponse) Descriptor() ([]byte, []int) {
	return file_material_proto_rawDescGZIP(), []int{12}
}

func (x *OrderResponse) GetStatus() OrderResponse_Status {
	if x != nil {
		return x.Status
	}
	return OrderResponse_OK
}

func (x *OrderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (m *OrderResponse) GetPayload() isOrderResponse_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *OrderResponse) GetError() string {
	if x, ok := x.GetPayload().(*OrderResponse_Error); ok {
		return x.Error
	}
	return ""
}

func (x *OrderResponse) GetData() string {
	if x, ok := x.GetPayload().(*OrderResponse_Data); ok {
		return x.Data
	}
	return ""
}

type isOrderResponse_Payload interface {
	isOrderResponse_Payload()
}

type OrderResponse_Error struct {
	Error string `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

type OrderResponse_Data struct {
	Data string `protobuf:"bytes,4,opt,name=data,proto3,oneof"`
}

func (*OrderResponse_Error) isOrderResponse_Payload() {}

func (*OrderResponse_Data) isOrderResponse_Payload() {}

var File_material_proto protoreflect.FileDescriptor

var file_material_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x70, 0x62, 0x22, 0x9e, 0x01, 0x0a, 0x08, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61,
	0x6c, 0x12, 0x1f, 0x0a, 0x0b, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x5f, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c,
	0x49, 0x44, 0x12, 0x23, 0x0a, 0x0d, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x5f, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x4d, 0x61, 0x74, 0x65, 0x72,
	0x69, 0x61, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x74, 0x6f,
	0x63, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x12,
	0x14, 0x0a, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05,
	0x50, 0x72, 0x69, 0x63, 0x65, 0x22, 0xb7, 0x01, 0x0a, 0x10, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69,
	0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x70, 0x62, 0x2e,
	0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x12, 0x14, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x1b, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52,
	0x4f, 0x52, 0x10, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22,
	0x12, 0x0a, 0x10, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x4e, 0x6f, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x73, 0x22, 0x3a, 0x0a, 0x0c, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x09, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x61, 0x74, 0x65,
	0x72, 0x69, 0x61, 0x6c, 0x52, 0x09, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x73, 0x22,
	0x1c, 0x0a, 0x0a, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x49, 0x44, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x49, 0x44, 0x22, 0x8e, 0x02,
	0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x17, 0x0a, 0x07, 0x49, 0x74, 0x65, 0x6d, 0x5f, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x44, 0x12,
	0x1b, 0x0a, 0x09, 0x49, 0x74, 0x65, 0x6d, 0x5f, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x49, 0x74, 0x65, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b,
	0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x5f, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0a, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x49, 0x44, 0x12, 0x16, 0x0a,
	0x06, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x4c,
	0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x57, 0x69, 0x64, 0x74, 0x68, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x57, 0x69, 0x64, 0x74, 0x68, 0x12, 0x22, 0x0a, 0x0d, 0x46,
	0x69, 0x78, 0x65, 0x64, 0x5f, 0x53, 0x69, 0x7a, 0x65, 0x5f, 0x49, 0x44, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0b, 0x46, 0x69, 0x78, 0x65, 0x64, 0x53, 0x69, 0x7a, 0x65, 0x49, 0x44, 0x12,
	0x1b, 0x0a, 0x09, 0x49, 0x73, 0x5f, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x08, 0x49, 0x73, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x12, 0x27, 0x0a, 0x0f,
	0x45, 0x73, 0x74, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0e, 0x45, 0x73, 0x74, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x64,
	0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x55, 0x73, 0x65, 0x72, 0x5f, 0x49, 0x44,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x22, 0xaf,
	0x01, 0x0a, 0x0c, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x2f, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x17, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x12, 0x14, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x1b, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52,
	0x52, 0x4f, 0x52, 0x10, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x22, 0x18, 0x0a, 0x06, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x44, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x49, 0x44, 0x22, 0x2a, 0x0a, 0x08, 0x49, 0x74,
	0x65, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x05, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52,
	0x05, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x0e, 0x0a, 0x0c, 0x49, 0x74, 0x65, 0x6d, 0x4e, 0x6f,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x22, 0xfb, 0x01, 0x0a, 0x05, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x12, 0x19, 0x0a, 0x08, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x44, 0x12, 0x17, 0x0a, 0x07, 0x55,
	0x73, 0x65, 0x72, 0x5f, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x12, 0x17, 0x0a, 0x07, 0x49, 0x74, 0x65, 0x6d, 0x5f, 0x49, 0x44, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x44, 0x12, 0x1a, 0x0a,
	0x08, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x5f, 0x63, 0x75, 0x74, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x43, 0x75, 0x74,
	0x12, 0x1b, 0x0a, 0x09, 0x49, 0x73, 0x5f, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x08, 0x49, 0x73, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x12, 0x16, 0x0a,
	0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x41,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74,
	0x5f, 0x49, 0x44, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x50, 0x61, 0x79, 0x6d, 0x65,
	0x6e, 0x74, 0x49, 0x44, 0x22, 0x2e, 0x0a, 0x09, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x21, 0x0a, 0x06, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x06, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x73, 0x22, 0xb1, 0x01, 0x0a, 0x0d, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x16, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x22, 0x1b, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b,
	0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x01, 0x42, 0x09, 0x0a,
	0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x32, 0xa5, 0x04, 0x0a, 0x0f, 0x4d, 0x61, 0x74,
	0x65, 0x72, 0x69, 0x61, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x30, 0x0a, 0x10,
	0x46, 0x69, 0x6e, 0x64, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x42, 0x79, 0x49, 0x44,
	0x12, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x49, 0x44,
	0x1a, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x12, 0x39,
	0x0a, 0x0f, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61,
	0x6c, 0x12, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x4e,
	0x6f, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x1a, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x61, 0x74,
	0x65, 0x72, 0x69, 0x61, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x07, 0x41, 0x64, 0x64,
	0x49, 0x74, 0x65, 0x6d, 0x12, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x1a, 0x10,
	0x2e, 0x70, 0x62, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x24, 0x0a, 0x0c, 0x46, 0x69, 0x6e, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x42, 0x79, 0x49, 0x44,
	0x12, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x44, 0x1a, 0x08, 0x2e, 0x70,
	0x62, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x2d, 0x0a, 0x11, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c,
	0x6c, 0x49, 0x74, 0x65, 0x6d, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x12, 0x0a, 0x2e, 0x70, 0x62,
	0x2e, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x44, 0x1a, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x74, 0x65,
	0x6d, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x0b, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c,
	0x49, 0x74, 0x65, 0x6d, 0x12, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x4e, 0x6f,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x1a, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x74, 0x65, 0x6d,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x08, 0x45, 0x64, 0x69, 0x74, 0x49, 0x74, 0x65, 0x6d,
	0x12, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x1a, 0x08, 0x2e, 0x70, 0x62, 0x2e,
	0x49, 0x74, 0x65, 0x6d, 0x12, 0x2a, 0x0a, 0x0a, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x49, 0x74,
	0x65, 0x6d, 0x12, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x44, 0x1a, 0x10,
	0x2e, 0x70, 0x62, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2a, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x09,
	0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x1a, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x0c,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x10, 0x2e, 0x70,
	0x62, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x4e, 0x6f, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x1a, 0x0d,
	0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x22, 0x0a,
	0x09, 0x46, 0x69, 0x6e, 0x64, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x0a, 0x2e, 0x70, 0x62, 0x2e,
	0x49, 0x74, 0x65, 0x6d, 0x49, 0x44, 0x1a, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x12, 0x2d, 0x0a, 0x10, 0x46, 0x69, 0x6e, 0x64, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x42,
	0x79, 0x55, 0x73, 0x65, 0x72, 0x12, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x49,
	0x44, 0x1a, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74,
	0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_material_proto_rawDescOnce sync.Once
	file_material_proto_rawDescData = file_material_proto_rawDesc
)

func file_material_proto_rawDescGZIP() []byte {
	file_material_proto_rawDescOnce.Do(func() {
		file_material_proto_rawDescData = protoimpl.X.CompressGZIP(file_material_proto_rawDescData)
	})
	return file_material_proto_rawDescData
}

var file_material_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_material_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_material_proto_goTypes = []any{
	(MaterialResponse_Status)(0), // 0: pb.MaterialResponse.Status
	(ItemResponse_Status)(0),     // 1: pb.ItemResponse.Status
	(OrderResponse_Status)(0),    // 2: pb.OrderResponse.Status
	(*Material)(nil),             // 3: pb.Material
	(*MaterialResponse)(nil),     // 4: pb.MaterialResponse
	(*MaterialNoParams)(nil),     // 5: pb.MaterialNoParams
	(*MaterialList)(nil),         // 6: pb.MaterialList
	(*MaterialID)(nil),           // 7: pb.MaterialID
	(*Item)(nil),                 // 8: pb.Item
	(*ItemResponse)(nil),         // 9: pb.ItemResponse
	(*ItemID)(nil),               // 10: pb.ItemID
	(*ItemList)(nil),             // 11: pb.ItemList
	(*ItemNoParams)(nil),         // 12: pb.ItemNoParams
	(*Order)(nil),                // 13: pb.Order
	(*OrderList)(nil),            // 14: pb.OrderList
	(*OrderResponse)(nil),        // 15: pb.OrderResponse
}
var file_material_proto_depIdxs = []int32{
	0,  // 0: pb.MaterialResponse.status:type_name -> pb.MaterialResponse.Status
	3,  // 1: pb.MaterialList.Materials:type_name -> pb.Material
	1,  // 2: pb.ItemResponse.status:type_name -> pb.ItemResponse.Status
	8,  // 3: pb.ItemList.Items:type_name -> pb.Item
	13, // 4: pb.OrderList.Orders:type_name -> pb.Order
	2,  // 5: pb.OrderResponse.status:type_name -> pb.OrderResponse.Status
	7,  // 6: pb.MaterialService.FindMaterialByID:input_type -> pb.MaterialID
	5,  // 7: pb.MaterialService.FindAllMaterial:input_type -> pb.MaterialNoParams
	8,  // 8: pb.MaterialService.AddItem:input_type -> pb.Item
	10, // 9: pb.MaterialService.FindItemByID:input_type -> pb.ItemID
	10, // 10: pb.MaterialService.FindAllItemByUser:input_type -> pb.ItemID
	12, // 11: pb.MaterialService.FindAllItem:input_type -> pb.ItemNoParams
	8,  // 12: pb.MaterialService.EditItem:input_type -> pb.Item
	10, // 13: pb.MaterialService.RemoveItem:input_type -> pb.ItemID
	13, // 14: pb.MaterialService.PlaceOrder:input_type -> pb.Order
	12, // 15: pb.MaterialService.OrderHistory:input_type -> pb.ItemNoParams
	10, // 16: pb.MaterialService.FindOrder:input_type -> pb.ItemID
	10, // 17: pb.MaterialService.FindOrdersByUser:input_type -> pb.ItemID
	3,  // 18: pb.MaterialService.FindMaterialByID:output_type -> pb.Material
	6,  // 19: pb.MaterialService.FindAllMaterial:output_type -> pb.MaterialList
	9,  // 20: pb.MaterialService.AddItem:output_type -> pb.ItemResponse
	8,  // 21: pb.MaterialService.FindItemByID:output_type -> pb.Item
	11, // 22: pb.MaterialService.FindAllItemByUser:output_type -> pb.ItemList
	11, // 23: pb.MaterialService.FindAllItem:output_type -> pb.ItemList
	8,  // 24: pb.MaterialService.EditItem:output_type -> pb.Item
	9,  // 25: pb.MaterialService.RemoveItem:output_type -> pb.ItemResponse
	15, // 26: pb.MaterialService.PlaceOrder:output_type -> pb.OrderResponse
	14, // 27: pb.MaterialService.OrderHistory:output_type -> pb.OrderList
	13, // 28: pb.MaterialService.FindOrder:output_type -> pb.Order
	14, // 29: pb.MaterialService.FindOrdersByUser:output_type -> pb.OrderList
	18, // [18:30] is the sub-list for method output_type
	6,  // [6:18] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_material_proto_init() }
func file_material_proto_init() {
	if File_material_proto != nil {
		return
	}
	file_material_proto_msgTypes[1].OneofWrappers = []any{
		(*MaterialResponse_Error)(nil),
		(*MaterialResponse_Data)(nil),
	}
	file_material_proto_msgTypes[6].OneofWrappers = []any{
		(*ItemResponse_Error)(nil),
		(*ItemResponse_Data)(nil),
	}
	file_material_proto_msgTypes[12].OneofWrappers = []any{
		(*OrderResponse_Error)(nil),
		(*OrderResponse_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_material_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_material_proto_goTypes,
		DependencyIndexes: file_material_proto_depIdxs,
		EnumInfos:         file_material_proto_enumTypes,
		MessageInfos:      file_material_proto_msgTypes,
	}.Build()
	File_material_proto = out.File
	file_material_proto_rawDesc = nil
	file_material_proto_goTypes = nil
	file_material_proto_depIdxs = nil
}
