name: CI for UserService

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  test-build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Go
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23.1  # Match your Go version

    # Run unit tests
    - name: Run Unit Tests
      run: |
        go test ./... -v

    # Check if it's a pull request
    - name: Check if it's a pull request
      id: check_pr
      run: echo "::set-output name=is_pr::$(test $GITHUB_EVENT_NAME = 'pull_request' && echo true || echo false)"

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      if: steps.check_pr.outputs.is_pr == 'false'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and push Docker image
    - name: Build and push Docker image
      if: steps.check_pr.outputs.is_pr == 'false'
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/userservice:v1.0 .
        docker push ${{ secrets.DOCKER_USERNAME }}/userservice:v1.0
