name: CI for UserService

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Go
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23.1  # Match your Go version

    # Run unit tests
    - name: Run Unit Tests
      run: |
        go test ./... -v

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Create .env file using GitHub secrets
    - name: Create .env file
      run: |
        echo "JWTKEY=${{ secrets.JWTKEY }}" >> .env
        echo "HOST=${{ secrets.HOST }}" >> .env
        echo "USER=${{ secrets.USER }}" >> .env
        echo "PASSWORD=${{ secrets.PASSWORD }}" >> .env
        echo "DBNAME=${{ secrets.DBNAME }}" >> .env
        echo "PORT=${{ secrets.PORT }}" >> .env
        echo "REDISHOST=${{ secrets.REDISHOST }}" >> .env
        echo "GRPCUSERPORT=${{ secrets.GRPCUSERPORT }}" >> .env
        echo "GRPCADMINPORT=${{ secrets.GRPCADMINPORT }}" >> .env
        echo "TWILIO_ACCOUNT_SID=${{ secrets.TWILIO_ACCOUNT_SID }}" >> .env
        echo "TWILIO_AUTH_TOKEN=${{ secrets.TWILIO_AUTH_TOKEN }}" >> .env
        echo "TWILIO_PHONE_NUMBER=${{ secrets.TWILIO_PHONE_NUMBER }}" >> .env
        echo "SERVICE_TOKEN=${{ secrets.SERVICE_TOKEN }}" >> .env

    # Build and push Docker image
    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/userservice:v1.0 .
        docker push ${{ secrets.DOCKER_USERNAME }}/userservice:v1.0
